/*
 * generated by Xtext
 */
package gov.ca.dwr.wresl.xtext.editor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WreslEditorRuntimeModule extends AbstractWreslEditorRuntimeModule {

}
