/*
 * generated by Xtext
 */
package gov.ca.dwr.wresl.xtext.editor.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class WreslEditorProposalProvider extends gov.ca.dwr.wresl.xtext.editor.ui.contentassist.AbstractWreslEditorProposalProvider {

}
